# Generated by Django 5.1.3 on 2024-12-02 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='services/images', verbose_name='Hover Imagen'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/images', verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='AdditionalServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='services.service')),
            ],
        ),
    ]
